### ISSUE TITLE
Use @urql/core as a foundation for gQuery

### ISSUE THREAD

**Issue by fezproof** [leveluptuts/gQuery#11]
I know this is a stretch and may be way out of scope for this library (which is awesome btw!), but using [`@urql/core`](https://formidable.com/open-source/urql/docs/basics/core) could be a great way to give this library a huge leg up.

The URQL team have done a great job at making a framework agnostic GraphQL client, that supports things like subscriptions and caching and other crazy stuff, and taking it and using it as a backbone for this library could be a match made in heaven. Plus it could reduce the amount of work to do that kind of stuff A LOT!

What are peoples thoughts on this?

*Some quick points*
- I know there is already a Svelte package for URQL, but it isn't the best with Svelte Kit and requires a lot of wacky stuff to get working with SSR and CSR at the same time.
- URQL uses [Wonka](https://wonka.kitten.sh) as its backbone, which can be a bit of a learning curve. However its api is super powerful, and has built in subscription support, which means making stores an absolute breeze

**Comment by jycouet** [comment]
Great topic, exactly on time! 👍 
I love the simplicity of this lib and thinking _a lot_ if I should use it now in the app I'm building or not. 


Today I started with `URQL`, and it's good. But 
- As you said, you need quite some code to make SSR and CSR. 
- You have to understand `exchanges`
- You have to decide how to work with caching... Normalized or Query based. (and I have strange behaviors in sveltekit today)


So, you loose a bit the easiness of `gQuery`?
At the same time I'm missing a few things in `gQuery`... But we could do a big boost? 🚀

**Comment by stolinski** [comment]
Def no plans to implement Urql or any other cache/ fetch library as it's pretty far removed from the concept of this library.
