### ISSUE TITLE
CORS issue when navigating between routes

### ISSUE THREAD

**Issue by csellis** [leveluptuts/gQuery#26]
GQuery works beautifully 💎 when doing a fresh load of a page, but I run into a CORS policy issue navigating between routes.

I'm fetching my posts from Hashnode. If I click a SvelteKit link to a different route, I get the following CSP Error:
```
[Report Only] Refused to connect to 'https://api.hashnode.com/' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:*".

Access to fetch at 'https://api.hashnode.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```
![Screenshot from 2022-02-13 15-33-30](https://user-images.githubusercontent.com/814405/153760544-baff452f-f44a-4af9-b88e-19ec4a85056c.png)

The `script` tags of my index.svelte: 
```
<script context="module">
  import { getAllPosts } from './AllPosts.gq';

  export async function load({ fetch }) {
    await getAllPosts({
      variables: {
        username: 'chrisellis',
      },
      fetch,
    });
    return {};
  }
</script>

<script>
  import { allPosts } from './AllPosts.gq';

  let { posts } = $allPosts.user.publication;
</script>
```

Open to any suggestions! 👍

**Comment by jycouet** [comment]
It's because gQuery enforce `credentials: "include"` in all fetchs.
The best would be to allow this configuration on client creation (like in https://github.com/jycouet/kitql).

In your case, you need `credentials: "omit"`

**Comment by csellis** [comment]
@jycouet Thank you! I've made an attempt to allow overwriting the options here, but I'm not sure if I'm on the right track.

https://github.com/csellis/gQuery/blob/db21035850bc33f8b82aefdad7d75d5d4234db76/src/gFetch.ts#L88

**Comment by jycouet** [comment]
You can do it now with: https://github.com/leveluptuts/gQuery/commit/b59400ee206bcb929f47c239bb1f257a3d2c3636 I guess 🙃

**Comment by stolinski** [comment]
This is now fixed. Sorry for the delay. You can now pass your own options into the fetch creds.
