### ISSUE TITLE
@leveluptuts/svelte-toy/Toy.svelte not found

### ISSUE THREAD

**Issue by timscodebase** [leveluptuts/gQuery#30]
When trying to run the example, I ran into a snag.  First I had this error `config.kit.target is no longer required, and should be removed` That was a quick and easy fix, just remove `target: '#svelte',` on line 11 of svelte.config.js.

Now I am seeing 
`✘ [ERROR] Could not resolve "@leveluptuts/svelte-toy/Toy.svelte"

    local-script:/Volumes/Storage/Code/Web/gQuery/example/src/lib/DevTools.svelte:9:7:
      9 │ import '@leveluptuts/svelte-toy/Toy.svelte'
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

and I do not know how to solve it.

**Comment by matmunn** [comment]
Have you installed https://www.npmjs.com/package/@leveluptuts/svelte-toy?

**Comment by stolinski** [comment]
This will be automatic in the next release, but for now you do need to install.
